// Generated by gencpp from file motor_management/comm.msg
// DO NOT EDIT!


#ifndef MOTOR_MANAGEMENT_MESSAGE_COMM_H
#define MOTOR_MANAGEMENT_MESSAGE_COMM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_management
{
template <class ContainerAllocator>
struct comm_
{
  typedef comm_<ContainerAllocator> Type;

  comm_()
    : motor_id(0)  {
    }
  comm_(const ContainerAllocator& _alloc)
    : motor_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _motor_id_type;
  _motor_id_type motor_id;





  typedef boost::shared_ptr< ::motor_management::comm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_management::comm_<ContainerAllocator> const> ConstPtr;

}; // struct comm_

typedef ::motor_management::comm_<std::allocator<void> > comm;

typedef boost::shared_ptr< ::motor_management::comm > commPtr;
typedef boost::shared_ptr< ::motor_management::comm const> commConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_management::comm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_management::comm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_management

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_management': ['/home/ubuntu/arle_ws/src/motor_management/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_management::comm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_management::comm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_management::comm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_management::comm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_management::comm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_management::comm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_management::comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a48abd1466f0e00748fbd1115ea80036";
  }

  static const char* value(const ::motor_management::comm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa48abd1466f0e007ULL;
  static const uint64_t static_value2 = 0x48fbd1115ea80036ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_management::comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_management/comm";
  }

  static const char* value(const ::motor_management::comm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_management::comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 motor_id\n\
\n\
";
  }

  static const char* value(const ::motor_management::comm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_management::comm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct comm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_management::comm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_management::comm_<ContainerAllocator>& v)
  {
    s << indent << "motor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_MANAGEMENT_MESSAGE_COMM_H
