// Generated by gencpp from file motor_management/command_mgr.msg
// DO NOT EDIT!


#ifndef MOTOR_MANAGEMENT_MESSAGE_COMMAND_MGR_H
#define MOTOR_MANAGEMENT_MESSAGE_COMMAND_MGR_H

#include <ros/service_traits.h>


#include <motor_management/command_mgrRequest.h>
#include <motor_management/command_mgrResponse.h>


namespace motor_management
{

struct command_mgr
{

typedef command_mgrRequest Request;
typedef command_mgrResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct command_mgr
} // namespace motor_management


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_management::command_mgr > {
  static const char* value()
  {
    return "ea9b8ec83958423851a8ad68108ef421";
  }

  static const char* value(const ::motor_management::command_mgr&) { return value(); }
};

template<>
struct DataType< ::motor_management::command_mgr > {
  static const char* value()
  {
    return "motor_management/command_mgr";
  }

  static const char* value(const ::motor_management::command_mgr&) { return value(); }
};


// service_traits::MD5Sum< ::motor_management::command_mgrRequest> should match 
// service_traits::MD5Sum< ::motor_management::command_mgr > 
template<>
struct MD5Sum< ::motor_management::command_mgrRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_management::command_mgr >::value();
  }
  static const char* value(const ::motor_management::command_mgrRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_management::command_mgrRequest> should match 
// service_traits::DataType< ::motor_management::command_mgr > 
template<>
struct DataType< ::motor_management::command_mgrRequest>
{
  static const char* value()
  {
    return DataType< ::motor_management::command_mgr >::value();
  }
  static const char* value(const ::motor_management::command_mgrRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_management::command_mgrResponse> should match 
// service_traits::MD5Sum< ::motor_management::command_mgr > 
template<>
struct MD5Sum< ::motor_management::command_mgrResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_management::command_mgr >::value();
  }
  static const char* value(const ::motor_management::command_mgrResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_management::command_mgrResponse> should match 
// service_traits::DataType< ::motor_management::command_mgr > 
template<>
struct DataType< ::motor_management::command_mgrResponse>
{
  static const char* value()
  {
    return DataType< ::motor_management::command_mgr >::value();
  }
  static const char* value(const ::motor_management::command_mgrResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_MANAGEMENT_MESSAGE_COMMAND_MGR_H
